### ISSUE TITLE
Crash on landscape mode

### ISSUE THREAD

**Issue by xmha97** [davidp799/patco-today#6]
Hi,
The app crashing on landscape mode randomly.
# Log
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
	at android.view.LayoutInflater.from(LayoutInflater.java:289)
	at android.widget.ArrayAdapter.<init>(ArrayAdapter.java:213)
	at android.widget.ArrayAdapter.<init>(ArrayAdapter.java:207)
	at android.widget.ArrayAdapter.<init>(ArrayAdapter.java:193)
	at com.davidp799.patcotoday.ui.schedules.SchedulesListAdapter.<init>(SchedulesListAdapter.java:39)
	at com.davidp799.patcotoday.ui.schedules.SchedulesFragment.updateSpecialData(SchedulesFragment.kt:290)
	at com.davidp799.patcotoday.ui.schedules.SchedulesFragment.setSpecialArrivals(SchedulesFragment.kt:513)
	at com.davidp799.patcotoday.ui.schedules.SchedulesFragment.access$setSpecialArrivals(SchedulesFragment.kt:32)
	at com.davidp799.patcotoday.ui.schedules.SchedulesFragment$setSpecialArrivalsOnMainThread$2.invokeSuspend(SchedulesFragment.kt:503)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8152)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@a672bb4, Dispatchers.IO]
```

**Comment by davidp799** [comment]
Hi, thanks for reporting this. This issue should now be fixed, and if not, feel free to reopen! :)
